"""Test Data Generator for Niv AI Dev Mode.

Generate realistic test/sample data for any DocType.
Usage in run_python_code:
    from niv_ai.niv_core.tools.test_data_gen import generate_test_data, generate_and_insert
"""
import frappe
import json
import random
import string
from datetime import datetime, timedelta


# Sample data pools
FIRST_NAMES = ["Rahul", "Priya", "Amit", "Sneha", "Vikram", "Neha", "Rajesh", "Pooja", "Suresh", "Anita",
               "Mahesh", "Kavita", "Deepak", "Sunita", "Ravi", "Meena", "Arun", "Geeta", "Sanjay", "Rekha"]
LAST_NAMES = ["Sharma", "Patel", "Singh", "Kumar", "Gupta", "Verma", "Joshi", "Agarwal", "Mehta", "Reddy",
              "Yadav", "Mishra", "Chauhan", "Pandey", "Thakur", "Dubey", "Saxena", "Tiwari", "Nair", "Iyer"]
CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Pune", "Kolkata", "Ahmedabad", "Jaipur", "Lucknow"]
STATES = ["Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "Telangana", "Gujarat", "West Bengal", "Rajasthan", "UP"]
COMPANIES = ["ABC Industries", "XYZ Corp", "Sharma Enterprises", "Global Tech", "Prime Solutions",
             "Star Manufacturing", "Delta Services", "Omega Trading", "Alpha Exports", "Beta Imports"]


def _random_name():
    return f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"

def _random_phone():
    return f"9{random.randint(100000000, 999999999)}"

def _random_email(name):
    clean = name.lower().replace(" ", ".").replace("'", "")
    return f"{clean}@{random.choice(['gmail.com', 'yahoo.com', 'outlook.com', 'company.com'])}"

def _random_date(days_back=365):
    d = datetime.now() - timedelta(days=random.randint(0, days_back))
    return d.strftime("%Y-%m-%d")

def _random_amount(min_val=1000, max_val=1000000):
    return round(random.uniform(min_val, max_val), 2)


def _generate_field_value(field, existing_links=None):
    """Generate a realistic value for a field based on its type."""
    ft = field.fieldtype
    fn = field.fieldname
    options = field.options or ""
    
    if ft == "Data":
        if "name" in fn.lower() or "customer_name" in fn.lower():
            return _random_name()
        if "email" in fn.lower():
            return _random_email(_random_name())
        if "phone" in fn.lower() or "mobile" in fn.lower():
            return _random_phone()
        if "city" in fn.lower():
            return random.choice(CITIES)
        if "state" in fn.lower():
            return random.choice(STATES)
        if "company" in fn.lower():
            return random.choice(COMPANIES)
        if "address" in fn.lower():
            return f"{random.randint(1,999)} {random.choice(['Main St', 'MG Road', 'Station Road', 'Park Avenue'])}, {random.choice(CITIES)}"
        return f"Test {fn} {random.randint(1, 999)}"
    
    elif ft == "Int":
        return random.randint(1, 100)
    
    elif ft in ("Float", "Currency"):
        if "rate" in fn.lower() or "percent" in fn.lower():
            return round(random.uniform(5, 25), 2)
        return _random_amount()
    
    elif ft == "Date":
        return _random_date()
    
    elif ft == "Datetime":
        return f"{_random_date()} {random.randint(8,18)}:{random.randint(0,59)}:00"
    
    elif ft == "Select":
        if options:
            choices = [o.strip() for o in options.split("\n") if o.strip()]
            return random.choice(choices) if choices else ""
        return ""
    
    elif ft == "Link":
        if existing_links and options in existing_links:
            links = existing_links[options]
            return random.choice(links) if links else None
        # Try to get existing records
        try:
            existing = frappe.get_all(options, limit=20, pluck="name")
            if existing:
                if existing_links is not None:
                    existing_links[options] = existing
                return random.choice(existing)
        except Exception:
            pass
        return None
    
    elif ft == "Check":
        return random.choice([0, 1])
    
    elif ft == "Small Text" or ft == "Text":
        return f"Sample {fn} text for testing purposes. Generated by Niv AI."
    
    elif ft == "Long Text" or ft == "Text Editor":
        return f"<p>This is sample {fn} content generated for testing. It contains enough text to be realistic.</p>"
    
    return None


def generate_test_data(doctype: str, count: int = 5, overrides: dict = None) -> list:
    """Generate test data records for a DocType (without inserting).
    
    Args:
        doctype: Target DocType
        count: Number of records to generate (max 20)
        overrides: Dict of field values to force (e.g., {'company': 'My Company'})
    
    Returns:
        list of dicts, each representing a document
    """
    count = min(count, 20)
    overrides = overrides or {}
    
    try:
        meta = frappe.get_meta(doctype)
    except Exception as e:
        return [{"error": f"DocType '{doctype}' not found: {str(e)}"}]
    
    # Get required and important fields
    fields = [f for f in meta.fields if f.fieldtype not in (
        "Section Break", "Column Break", "Tab Break", "HTML", "Heading",
        "Button", "Fold", "Read Only"
    )]
    
    required_fields = [f for f in fields if f.reqd]
    optional_fields = [f for f in fields if not f.reqd and f.fieldname not in (
        "naming_series", "amended_from", "amendment_date"
    )]
    
    existing_links = {}
    records = []
    
    for _ in range(count):
        record = {"doctype": doctype}
        
        # Fill required fields
        for field in required_fields:
            if field.fieldname in overrides:
                record[field.fieldname] = overrides[field.fieldname]
            else:
                val = _generate_field_value(field, existing_links)
                if val is not None:
                    record[field.fieldname] = val
        
        # Fill some optional fields (50% chance each)
        for field in optional_fields[:15]:  # Cap at 15 optional fields
            if field.fieldname in overrides:
                record[field.fieldname] = overrides[field.fieldname]
            elif random.random() > 0.5:
                val = _generate_field_value(field, existing_links)
                if val is not None:
                    record[field.fieldname] = val
        
        records.append(record)
    
    return records


def generate_and_insert(doctype: str, count: int = 5, overrides: dict = None, dry_run: bool = True) -> dict:
    """Generate and optionally insert test data.
    
    Args:
        doctype: Target DocType
        count: Number of records (max 20)
        overrides: Field value overrides
        dry_run: If True, only generate without inserting
    
    Returns:
        dict with generated/inserted records
    """
    records = generate_test_data(doctype, count, overrides)
    
    if dry_run:
        return {
            "status": "preview",
            "message": f"Would create {len(records)} {doctype} test records",
            "records": records,
            "note": "Call with dry_run=False to insert"
        }
    
    inserted = []
    errors = []
    for record in records:
        try:
            doc = frappe.get_doc(record)
            doc.insert(ignore_permissions=False)
            inserted.append(doc.name)
        except Exception as e:
            errors.append({"error": str(e), "data": {k: v for k, v in record.items() if k != "doctype"}})
    
    frappe.db.commit()
    
    return {
        "status": "success",
        "message": f"Inserted {len(inserted)}/{len(records)} {doctype} test records",
        "inserted": inserted,
        "errors": errors[:5] if errors else []
    }
